import {
  Apple,
  Brain,
  ClipboardCheck,
  FileText,
  FlaskConical,
  Ruler,
  Stethoscope,
  Target,
  User,
} from "lucide-react";

export const workspaceTabs = [
  { id: "summary", label: "Summary", icon: User },
  { id: "anthropometric", label: "Anthropometric Assessment", icon: Ruler },
  { id: "laboratory", label: "Laboratory Results", icon: FlaskConical },
  { id: "dietary", label: "Dietary Assessment", icon: Apple },
  { id: "medical", label: "Medical History", icon: Stethoscope },
  { id: "pes", label: "Nutrition Diagnosis (PES)", icon: FileText },
  { id: "intervention", label: "Nutrition Intervention", icon: Target },
  { id: "monitoring", label: "Monitoring & Evaluation", icon: ClipboardCheck },
  { id: "ai", label: "AI Insights", icon: Brain },
];

export const sampleWorkspaceData = {
  summary: [
    ["Primary concern", "Iron deficiency with IBS history"],
    ["Nutrition risk", "Moderate"],
    ["Visit type", "Initial assessment"],
    ["Care priority", "Review intake, symptoms, and lab trends"],
  ],
  anthropometric: [
    ["Current weight", "Recorded at intake"],
    ["Usual body weight", "Pending patient interview"],
    ["Weight change", "To be documented"],
    ["Waist circumference", "Pending measurement"],
    ["MUAC", "Pending measurement"],
    ["Body composition", "Not assessed yet"],
  ],
  laboratory: [
    ["Ferritin", "12 ng/mL - low"],
    ["Hemoglobin", "11.2 g/dL - low"],
    ["Vitamin D", "20 ng/mL - review"],
    ["Albumin", "Within expected range"],
    ["CRP", "Pending"],
    ["B12 / Folate", "Pending"],
  ],
  dietary: [
    ["24-hour recall", "Incomplete"],
    ["Meal pattern", "Irregular meals reported"],
    ["Fiber intake", "Low intake suspected"],
    ["Iron-rich foods", "Needs detailed review"],
    ["Fluid intake", "Pending"],
    ["Supplement use", "Not recorded"],
  ],
  medical: [
    ["Medical diagnosis", "IBS, iron deficiency"],
    ["GI symptoms", "Bloating and discomfort"],
    ["Medication history", "Pending reconciliation"],
    ["Allergies", "No allergy documented"],
    ["Bowel pattern", "Needs assessment"],
    ["Functional status", "Independent"],
  ],
  pes: [
    ["Problem", "Inadequate iron intake"],
    ["Etiology", "Possible reduced intake and gastrointestinal tolerance issues"],
    ["Signs / Symptoms", "Low ferritin, low hemoglobin, fatigue"],
    ["Draft status", "Requires clinician review"],
  ],
  intervention: [
    ["Nutrition goal", "Improve iron status and GI tolerance"],
    ["Diet strategy", "Iron-rich meals with absorption support"],
    ["Education", "Food sources, timing, and symptom monitoring"],
    ["Coordination", "Follow-up labs and physician communication"],
  ],
  monitoring: [
    ["Follow-up interval", "4 weeks"],
    ["Lab monitoring", "Ferritin, hemoglobin, vitamin D"],
    ["Symptoms", "Bloating, fatigue, bowel pattern"],
    ["Adherence", "Meal pattern and supplement tolerance"],
  ],
  ai: [
    ["Detected pattern", "Iron deficiency profile with GI context"],
    ["Confidence", "Moderate"],
    ["Suggested review", "Dietary iron intake and absorption factors"],
    ["Next best action", "Complete dietary recall and repeat labs plan"],
  ],
};

export const anthropometricDefaults = {
  height: "",
  weight: "",
  age: "",
  gender: "",
  usualBodyWeight: "",
  idealBodyWeight: "",
  activityFactor: "1.2",
  stressFactor: "1.1",
  muac: "",
  tsf: "",
  waistCircumference: "",
  hipCircumference: "",
};

export const labReferenceRanges = [
  {
    key: "hemoglobin",
    label: "Hemoglobin (Hb)",
    unit: "g/dL",
    normalLow: 12,
    normalHigh: 16,
    criticalLow: 8,
    criticalHigh: 20,
    lowText: "Low hemoglobin may indicate anemia risk and requires clinical correlation.",
    highText: "High hemoglobin may require hydration and medical status review.",
  },
  {
    key: "ferritin",
    label: "Ferritin",
    unit: "ng/mL",
    normalLow: 15,
    normalHigh: 150,
    criticalLow: 10,
    criticalHigh: 300,
    lowText: "Low ferritin suggests depleted iron stores and possible iron deficiency.",
    highText: "High ferritin may reflect inflammation or iron overload risk.",
  },
  {
    key: "serumIron",
    label: "Serum Iron",
    unit: "mcg/dL",
    normalLow: 60,
    normalHigh: 170,
    criticalLow: 35,
    criticalHigh: 220,
    lowText: "Low serum iron supports possible iron deficiency pattern.",
    highText: "High serum iron requires follow-up with iron studies.",
  },
  {
    key: "tibc",
    label: "TIBC",
    unit: "mcg/dL",
    normalLow: 240,
    normalHigh: 450,
    criticalLow: 180,
    criticalHigh: 520,
    lowText: "Low TIBC may require inflammation or chronic disease review.",
    highText: "High TIBC may support iron deficiency risk.",
  },
  {
    key: "transferrinSaturation",
    label: "Transferrin Saturation",
    unit: "%",
    normalLow: 20,
    normalHigh: 50,
    criticalLow: 12,
    criticalHigh: 60,
    lowText: "Low transferrin saturation may indicate insufficient available iron.",
    highText: "High transferrin saturation requires follow-up iron evaluation.",
  },
  {
    key: "albumin",
    label: "Albumin",
    unit: "g/dL",
    normalLow: 3.5,
    normalHigh: 5,
    criticalLow: 2.8,
    criticalHigh: 5.5,
    lowText: "Low albumin may reflect inflammation, fluid shifts, or protein status concerns.",
    highText: "High albumin may suggest dehydration and needs context review.",
  },
  {
    key: "prealbumin",
    label: "Prealbumin",
    unit: "mg/dL",
    normalLow: 16,
    normalHigh: 35,
    criticalLow: 10,
    criticalHigh: 45,
    lowText: "Low prealbumin may indicate acute nutrition or inflammatory concerns.",
    highText: "High prealbumin is uncommon and requires clinical context.",
  },
  {
    key: "vitaminD",
    label: "Vitamin D",
    unit: "ng/mL",
    normalLow: 30,
    normalHigh: 100,
    criticalLow: 20,
    criticalHigh: 120,
    lowText: "Low vitamin D suggests deficiency risk and supplementation review.",
    highText: "High vitamin D may indicate excess intake and requires follow-up.",
  },
  {
    key: "vitaminB12",
    label: "Vitamin B12",
    unit: "pg/mL",
    normalLow: 200,
    normalHigh: 900,
    criticalLow: 150,
    criticalHigh: 1200,
    lowText: "Low B12 may contribute to anemia or neurological symptoms.",
    highText: "High B12 requires review of supplementation and clinical context.",
  },
  {
    key: "folate",
    label: "Folate",
    unit: "ng/mL",
    normalLow: 3,
    normalHigh: 20,
    criticalLow: 2,
    criticalHigh: 25,
    lowText: "Low folate may contribute to anemia risk.",
    highText: "High folate requires supplementation review.",
  },
  {
    key: "calcium",
    label: "Calcium",
    unit: "mg/dL",
    normalLow: 8.5,
    normalHigh: 10.5,
    criticalLow: 7.5,
    criticalHigh: 12,
    lowText: "Low calcium requires mineral and vitamin D context review.",
    highText: "High calcium requires medical follow-up.",
  },
  {
    key: "magnesium",
    label: "Magnesium",
    unit: "mg/dL",
    normalLow: 1.7,
    normalHigh: 2.2,
    criticalLow: 1.2,
    criticalHigh: 3,
    lowText: "Low magnesium may affect metabolic and muscle function.",
    highText: "High magnesium requires renal and supplement review.",
  },
  {
    key: "zinc",
    label: "Zinc",
    unit: "mcg/dL",
    normalLow: 60,
    normalHigh: 130,
    criticalLow: 45,
    criticalHigh: 160,
    lowText: "Low zinc may affect appetite, wound healing, and immunity.",
    highText: "High zinc requires supplement review.",
  },
  {
    key: "sodium",
    label: "Sodium",
    unit: "mmol/L",
    normalLow: 135,
    normalHigh: 145,
    criticalLow: 125,
    criticalHigh: 155,
    lowText: "Low sodium requires hydration and medical review.",
    highText: "High sodium may indicate dehydration or medical imbalance.",
  },
  {
    key: "potassium",
    label: "Potassium",
    unit: "mmol/L",
    normalLow: 3.5,
    normalHigh: 5.1,
    criticalLow: 3,
    criticalHigh: 6,
    lowText: "Low potassium requires electrolyte and intake review.",
    highText: "High potassium requires urgent clinical context review.",
  },
  {
    key: "fastingGlucose",
    label: "Fasting Glucose",
    unit: "mg/dL",
    normalLow: 70,
    normalHigh: 99,
    criticalLow: 55,
    criticalHigh: 180,
    lowText: "Low glucose requires intake and medication context review.",
    highText: "High fasting glucose suggests glucose control risk.",
  },
  {
    key: "hba1c",
    label: "HbA1c",
    unit: "%",
    normalLow: 4,
    normalHigh: 5.6,
    criticalLow: 3.5,
    criticalHigh: 8,
    lowText: "Low HbA1c requires clinical context review.",
    highText: "High HbA1c suggests elevated glucose control risk.",
  },
  {
    key: "totalCholesterol",
    label: "Total Cholesterol",
    unit: "mg/dL",
    normalLow: 0,
    normalHigh: 199,
    criticalLow: 0,
    criticalHigh: 240,
    lowText: "Low cholesterol requires broader nutrition and medical context.",
    highText: "High total cholesterol suggests dyslipidemia risk.",
  },
  {
    key: "ldl",
    label: "LDL",
    unit: "mg/dL",
    normalLow: 0,
    normalHigh: 99,
    criticalLow: 0,
    criticalHigh: 160,
    lowText: "Low LDL is usually not a nutrition concern without context.",
    highText: "High LDL suggests dyslipidemia risk.",
  },
  {
    key: "hdl",
    label: "HDL",
    unit: "mg/dL",
    normalLow: 40,
    normalHigh: 90,
    criticalLow: 35,
    criticalHigh: 110,
    lowText: "Low HDL may contribute to cardiometabolic risk.",
    highText: "High HDL generally requires context review only.",
  },
  {
    key: "triglycerides",
    label: "Triglycerides",
    unit: "mg/dL",
    normalLow: 0,
    normalHigh: 149,
    criticalLow: 0,
    criticalHigh: 500,
    lowText: "Low triglycerides require clinical context if symptomatic.",
    highText: "High triglycerides suggest dyslipidemia risk.",
  },
  {
    key: "crp",
    label: "CRP",
    unit: "mg/L",
    normalLow: 0,
    normalHigh: 3,
    criticalLow: 0,
    criticalHigh: 10,
    lowText: "Low CRP is typically not concerning.",
    highText: "High CRP suggests inflammation and affects nutrition marker interpretation.",
  },
];

export const labDefaults = labReferenceRanges.reduce((defaults, lab) => {
  defaults[lab.key] = "";
  return defaults;
}, {});

export const dietaryMealFields = [
  { key: "breakfast", label: "Breakfast" },
  { key: "snack1", label: "Snack 1" },
  { key: "lunch", label: "Lunch" },
  { key: "snack2", label: "Snack 2" },
  { key: "dinner", label: "Dinner" },
  { key: "lateSnack", label: "Late snack" },
];

export const dietaryAssessmentFields = [
  { key: "mealPattern", label: "Meal pattern", type: "select", options: ["Regular", "Irregular", "Skipped meals", "Small frequent meals"] },
  { key: "appetiteLevel", label: "Appetite level", type: "select", options: ["Good", "Fair", "Poor", "Variable"] },
  { key: "foodAllergies", label: "Food allergies", type: "text" },
  { key: "foodIntolerances", label: "Food intolerances", type: "text" },
  { key: "supplements", label: "Supplements", type: "text" },
  { key: "waterIntake", label: "Water intake", type: "select", options: ["Less than 1 L/day", "1-1.5 L/day", "1.5-2 L/day", "More than 2 L/day"] },
  { key: "caffeineIntake", label: "Caffeine intake", type: "select", options: ["None", "1 cup/day", "2-3 cups/day", "More than 3 cups/day"] },
  { key: "bowelHabits", label: "Bowel habits", type: "select", options: ["Regular", "Constipation", "Diarrhea", "Alternating pattern"] },
  { key: "nauseaVomiting", label: "Nausea / vomiting", type: "select", options: ["None", "Occasional nausea", "Frequent nausea", "Vomiting reported"] },
  { key: "chewingSwallowing", label: "Chewing or swallowing problems", type: "select", options: ["None", "Chewing difficulty", "Swallowing difficulty", "Requires texture modification"] },
  { key: "foodPreferences", label: "Food preferences", type: "text" },
  { key: "culturalReligious", label: "Cultural / religious food considerations", type: "text" },
  { key: "nutritionBarriers", label: "Nutrition barriers", type: "textarea" },
];

export const dietaryDefaults = {
  breakfast: "Low-fat yogurt with tea",
  snack1: "None reported",
  lunch: "Rice with chicken, small salad",
  snack2: "Biscuits or fruit occasionally",
  dinner: "Soup or sandwich",
  lateSnack: "None",
  mealPattern: "Irregular",
  appetiteLevel: "Fair",
  foodAllergies: "No known food allergy",
  foodIntolerances: "Possible lactose sensitivity",
  supplements: "Vitamin D supplement under review",
  waterIntake: "1-1.5 L/day",
  caffeineIntake: "2-3 cups/day",
  bowelHabits: "Alternating pattern",
  nauseaVomiting: "None",
  chewingSwallowing: "None",
  foodPreferences: "Prefers simple home meals",
  culturalReligious: "Halal diet pattern",
  nutritionBarriers: "Bloating after some meals and inconsistent meal timing.",
};

export const medicalHistoryFields = [
  { key: "primaryDiagnosis", label: "Primary diagnosis", type: "text" },
  { key: "secondaryDiagnoses", label: "Secondary diagnoses", type: "textarea" },
  { key: "pastMedicalHistory", label: "Past medical history", type: "textarea" },
  { key: "surgicalHistory", label: "Surgical history", type: "textarea" },
  { key: "medicationList", label: "Medication list", type: "textarea" },
  { key: "supplements", label: "Supplements", type: "text" },
  { key: "allergies", label: "Allergies", type: "text" },
  { key: "familyHistory", label: "Family history", type: "textarea" },
  { key: "giSymptoms", label: "GI symptoms", type: "textarea" },
  { key: "bowelMovementPattern", label: "Bowel movement pattern", type: "select", options: ["Regular", "Constipation", "Diarrhea", "Alternating pattern", "Needs assessment"] },
  { key: "physicalActivityLevel", label: "Physical activity level", type: "select", options: ["Sedentary", "Light", "Moderate", "Active", "Needs assessment"] },
  { key: "smokingStatus", label: "Smoking status", type: "select", options: ["Never smoker", "Former smoker", "Current smoker", "Not documented"] },
  { key: "sleepQuality", label: "Sleep quality", type: "select", options: ["Good", "Fair", "Poor", "Not documented"] },
  { key: "recentWeightChanges", label: "Recent weight changes", type: "text" },
  { key: "nutritionRelatedSymptoms", label: "Nutrition-related symptoms", type: "textarea" },
];

export const medicalStructuredFields = [
  { key: "diagnosis", label: "Diagnosis", type: "text" },
  { key: "diagnosisDate", label: "Diagnosis date", type: "date" },
  { key: "currentMedications", label: "Current medications", type: "textarea" },
  { key: "medicationNutrientNotes", label: "Medication-nutrient interactions notes", type: "textarea" },
  { key: "foodDrugAllergies", label: "Food/drug allergies", type: "text" },
  { key: "relevantSurgeries", label: "Relevant surgeries", type: "textarea" },
  { key: "giComplaints", label: "GI complaints", type: "textarea" },
  { key: "physicalActivity", label: "Physical activity", type: "text" },
  { key: "lifestyleNotes", label: "Lifestyle notes", type: "textarea" },
];

export const medicalHistoryDefaults = {
  primaryDiagnosis: "Irritable Bowel Syndrome",
  secondaryDiagnoses: "Iron deficiency, vitamin D insufficiency under review",
  pastMedicalHistory: "No chronic disease documented beyond current diagnosis.",
  surgicalHistory: "No relevant surgery reported.",
  medicationList: "Antispasmodic as needed; iron supplement tolerance under review.",
  supplements: "Vitamin D supplement, occasional multivitamin",
  allergies: "No known drug allergy documented",
  familyHistory: "Family history of diabetes reported by patient.",
  giSymptoms: "Bloating, abdominal discomfort after selected meals.",
  bowelMovementPattern: "Alternating pattern",
  physicalActivityLevel: "Light",
  smokingStatus: "Never smoker",
  sleepQuality: "Fair",
  recentWeightChanges: "Reports mild weight gain over recent months.",
  nutritionRelatedSymptoms: "Fatigue, bloating, variable appetite.",
  diagnosis: "IBS with iron deficiency pattern",
  diagnosisDate: "2026-01-15",
  currentMedications: "Antispasmodic PRN; oral iron supplement under consideration.",
  medicationNutrientNotes: "Separate iron from tea/coffee and calcium-rich meals when clinically appropriate.",
  foodDrugAllergies: "No food/drug allergy confirmed",
  relevantSurgeries: "None reported",
  giComplaints: "Bloating and variable bowel pattern",
  physicalActivity: "Light walking 2-3 times weekly",
  lifestyleNotes: "Irregular meal timing, moderate caffeine intake, sleep quality fair.",
};

export const nutritionDiagnosisTerms = {
  problem: [
    "Inadequate energy intake",
    "Inadequate protein-energy intake",
    "Excessive energy intake",
    "Altered nutrition-related laboratory values",
    "Unintended weight loss",
    "Overweight/obesity",
    "Food and nutrition-related knowledge deficit",
    "Inadequate oral intake",
    "Impaired nutrient utilization",
    "Inadequate fluid intake",
    "Inadequate fiber intake",
    "Inadequate iron intake",
    "Altered gastrointestinal function",
    "Malnutrition risk",
  ],
  etiology: [
    "related to reduced appetite",
    "related to increased metabolic demand",
    "related to poor dietary habits",
    "related to gastrointestinal symptoms",
    "related to limited nutrition knowledge",
    "related to chronic disease condition",
    "related to medication side effects",
    "related to restricted food access",
    "related to irregular meal pattern",
    "related to limited intake of iron-rich foods",
    "related to excessive intake of energy-dense foods",
    "related to limited physical activity",
  ],
  signsSymptoms: [
    "as evidenced by low BMI",
    "as evidenced by recent weight loss",
    "as evidenced by abnormal laboratory values",
    "as evidenced by low dietary intake",
    "as evidenced by high BMI",
    "as evidenced by elevated glucose",
    "as evidenced by low ferritin",
    "as evidenced by patient reported symptoms",
    "as evidenced by low hemoglobin",
    "as evidenced by low vitamin D",
    "as evidenced by reported fatigue",
    "as evidenced by reported bloating",
  ],
};

export const pesDefaults = {
  problem: "Altered nutrition-related laboratory values",
  etiology: "related to chronic disease condition",
  signsSymptoms: "as evidenced by low ferritin",
  priority: "Moderate",
  status: "Active",
};

export const interventionGoalChips = [
  "Improve oral intake",
  "Correct iron deficiency",
  "Support weight gain",
  "Support weight loss",
  "Improve glycemic control",
  "Reduce GI symptoms",
  "Improve vitamin D status",
  "Preserve lean body mass",
];

export const interventionDefaults = {
  nutritionGoals: "Improve intake quality, correct nutrition deficits, and support clinical stability.",
  energyPrescription: "Estimate individualized energy needs after anthropometric assessment review.",
  proteinPrescription: "Provide protein across meals and adjust based on clinical status.",
  fluidPrescription: "Encourage regular fluid intake unless medically restricted.",
  dietType: "Balanced oral diet with symptom-aware modifications.",
  mealPattern: "Three meals with planned snacks as tolerated.",
  supplements: "Review iron and vitamin D supplementation need with the clinical team.",
  foodRestrictions: "Avoid patient-specific trigger foods and unnecessary restrictions.",
  nutritionEducation: "Educate on nutrient-dense meals, iron absorption, hydration, and symptom tracking.",
  counselingNotes: "Use patient-centered counseling and address barriers to adherence.",
  followUpPlan: "Follow up in 2-4 weeks to review intake, symptoms, weight trend, and labs.",
};

export const monitoringDefaults = {
  visitDate: "",
  weight: "",
  bmi: "",
  appetiteStatus: "Fair",
  dietaryCompliance: "Moderate",
  symptoms: "Symptoms stable with no urgent concerns reported.",
  labChanges: "No updated labs recorded.",
  goalsAchieved: "Partial progress toward nutrition goals.",
  clinicalNotes: "Continue monitoring intake, symptoms, weight trend, and lab follow-up.",
  nextFollowUpDate: "",
  progressStatus: "Stable",
};

export const progressStatusOptions = [
  "Improving",
  "Stable",
  "Worsening",
  "Needs urgent review",
];
